import { useEffect, useMemo, useRef, useState } from 'react'
import { get, set } from 'idb-keyval'
import { CashPayment, cashPaymentsTotal, validCashPayment } from '../payments'
import { commitCashPayments, watchCashPayments } from '../payment-cloud'
import { Customer, Sale, fmtBRL, uid } from '../types'
import './Payments.css'

const today = () => new Date().toLocaleDateString('sv-SE', { timeZone: 'America/Sao_Paulo' })
const blank = (): CashPayment => ({ id: uid(), amount: 0, description: '', person: '', date: today() })

export function PaymentsView({ owner, sales, customers, pushToast }: { owner: string; sales: Sale[]; customers: Customer[]; pushToast: (text: string, type?: 'success' | 'error') => void }) {
  const key = `cc_payments:${owner.toLowerCase()}`
  const [payments, setPayments] = useState<CashPayment[]>([]), [ready, setReady] = useState(false), [form, setForm] = useState(blank), [editing, setEditing] = useState<string | null>(null), [busy, setBusy] = useState(false)
  const current = useRef<CashPayment[]>([]); current.current = payments
  useEffect(() => { let stopped = false; let stop = () => {}; void (async () => { try { const saved = await get(key); const local = Array.isArray(saved) && saved.every(validCashPayment) ? saved : []; stop = watchCashPayments((rows) => { if (!stopped) { setPayments(rows); setReady(true); void set(key, rows) } }, () => { if (!stopped) { setPayments(local); setReady(true); pushToast('Pagamentos estão disponíveis apenas neste aparelho até a sincronização voltar.', 'error') } }) } catch { if (!stopped) setReady(true) } })(); return () => { stopped = true; stop() } }, [key])
  const cookieDebits = useMemo(() => sales.filter(s => s.status === 'Debitado').map(s => ({ id: s.id, quantity: s.items.reduce((n, i) => n + i.qty, 0), amount: s.total, description: s.items.map(i => `${i.qty}x ${i.name}`).join(' + '), person: customers.find(c => c.id === s.customerId)?.name || 'Pessoa não informada', date: s.date.slice(0, 10) })).sort((a, b) => b.date.localeCompare(a.date)), [sales, customers])
  const savePayment = async (event: React.FormEvent) => { event.preventDefault(); const next = { ...form, amount: Number(form.amount) }; if (!validCashPayment(next)) return pushToast('Informe valor, motivo, pessoa e data válidos.', 'error'); setBusy(true); try { const after = editing ? payments.map(p => p.id === editing ? next : p) : [...payments, next]; await commitCashPayments(payments, after); setForm(blank()); setEditing(null); pushToast(editing ? 'Pagamento atualizado.' : 'Pagamento registrado.') } catch (error) { pushToast(error instanceof Error ? error.message : 'Não foi possível salvar o pagamento.', 'error') } finally { setBusy(false) } }
  const remove = async (p: CashPayment) => { if (!confirm(`Excluir o pagamento de ${fmtBRL(p.amount)}? Ele ficará preservado no histórico.`)) return; setBusy(true); try { await commitCashPayments(payments, payments.map(item => item.id === p.id ? { ...item, archived: true } : item)); if (editing === p.id) { setEditing(null); setForm(blank()) }; pushToast('Pagamento excluído e mantido no histórico.') } catch { pushToast('Não foi possível excluir o pagamento.', 'error') } finally { setBusy(false) } }
  const cashTotal = cashPaymentsTotal(payments), cookieTotal = cookieDebits.reduce((sum, item) => sum + item.amount, 0)
  if (!ready) return <p role="status">Abrindo pagamentos…</p>
  return <div className="payments-view"><header className="page-title"><h1>Pagamentos</h1><p>Saídas em dinheiro e cookies debitados, mantidos no histórico.</p></header><dl className="payment-summary"><div><dt>Em dinheiro</dt><dd>{fmtBRL(cashTotal)}</dd></div><div><dt>Cookies debitados</dt><dd>{fmtBRL(cookieTotal)}</dd></div><div className="payment-total"><dt>Total pago/debitado</dt><dd>{fmtBRL(cashTotal + cookieTotal)}</dd></div></dl><section className="payment-card"><h2>{editing ? 'Editar pagamento em dinheiro' : 'Registrar pagamento em dinheiro'}</h2><form className="payment-form" onSubmit={savePayment}><label>Valor (R$)<input type="number" min="0.01" step="0.01" value={form.amount || ''} onChange={e => setForm({ ...form, amount: Number(e.target.value) })} required /></label><label>Motivo / descrição<input maxLength={500} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} required /></label><label>Pessoa<input maxLength={200} value={form.person} onChange={e => setForm({ ...form, person: e.target.value })} required /></label><label>Data<input type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} required /></label><div className="payment-actions"><button className="btn btn-primary" disabled={busy}>{editing ? 'Salvar alterações' : 'Adicionar pagamento'}</button>{editing && <button type="button" className="btn btn-ghost" onClick={() => { setEditing(null); setForm(blank()) }}>Cancelar</button>}</div></form></section><PaymentList title="Pagamentos em dinheiro" empty="Nenhum pagamento em dinheiro registrado." rows={payments.filter(p => !p.archived).sort((a, b) => b.date.localeCompare(a.date))} cash onEdit={p => { setForm(p); setEditing(p.id) }} onDelete={p => void remove(p)} /><PaymentList title="Cookies debitados" empty="Nenhum cookie debitado." rows={cookieDebits} /><PaymentList title="Histórico de pagamentos excluídos" empty="Nenhum pagamento excluído." rows={payments.filter(p => p.archived).sort((a, b) => b.date.localeCompare(a.date))} cash /></div>
}
function PaymentList({ title, empty, rows, cash, onEdit, onDelete }: { title: string; empty: string; rows: Array<{ id: string; amount: number; description: string; person: string; date: string; quantity?: number }>; cash?: boolean; onEdit?: (p: CashPayment) => void; onDelete?: (p: CashPayment) => void }) { return <section className="payment-card"><div className="payment-section-title"><h2>{title}</h2><span className={`payment-kind ${cash ? 'cash' : 'cookies'}`}>{cash ? 'Dinheiro' : 'Cookies'}</span></div>{!cash && <p className="payment-source">Gerados automaticamente pelas vendas marcadas como debitadas.</p>}{rows.length ? <div className="payment-table-wrap"><table className="payment-table"><thead><tr>{!cash && <th>Qtd.</th>}<th>Valor</th><th>Motivo / descrição</th><th>Pessoa</th><th>Data</th>{cash && <th>Ações</th>}</tr></thead><tbody>{rows.map(row => <tr key={row.id}>{!cash && <td data-label="Quantidade">{row.quantity}</td>}<td data-label="Valor">{fmtBRL(row.amount)}</td><td data-label="Motivo">{row.description}</td><td data-label="Pessoa">{row.person}</td><td data-label="Data">{row.date.split('-').reverse().join('/')}</td>{cash && <td data-label="Ações"><button className="btn btn-ghost" onClick={() => onEdit?.(row as CashPayment)}>Editar</button><button className="btn btn-ghost" onClick={() => onDelete?.(row as CashPayment)}>Excluir</button></td>}</tr>)}</tbody></table></div> : <p className="payment-empty">{empty}</p>}</section> }
