import { useState } from 'react'
import { IngredientPurchase, normalizeIngredient, normalizedPrice, paymentLabel, priceStats, purchaseDue } from '../ingredients'
import { fmtBRL } from '../types'
export function PurchasePrices({ purchases }: { purchases: IngredientPurchase[] }) {
  const [product, setProduct] = useState(''), [shop, setShop] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState(''), [status, setStatus] = useState('all'), [unit, setUnit] = useState('')
  const active = purchases.filter(p => !p.archived)
  const products = [...new Map(active.flatMap(p => p.items.map(i => [normalizeIngredient(i.name), i.name.trim()] as const)))].sort((a,b) => a[1].localeCompare(b[1]))
  const shops = [...new Map(active.map(p => [normalizeIngredient(p.shop), p.shop.trim()] as const))].filter(([key]) => key).sort((a,b) => a[1].localeCompare(b[1]))
  const rows = active.filter(p => (!shop || normalizeIngredient(p.shop) === shop) && (!from || p.date >= from) && (!to || p.date <= to) && (status === 'all' || (purchaseDue(p) > 0 ? 'pending' : 'paid') === status)).flatMap(p => p.items.map((item,index) => ({ p, item, index, price: normalizedPrice(item) }))).filter(r => !product || normalizeIngredient(r.item.name) === product).sort((a,b) => b.p.date.localeCompare(a.p.date))
  const units = [...new Set(rows.flatMap(r => r.price ? [r.price.unit] : []))]
  const basis = unit === 'line' || units.includes(unit as 'kg' | 'l' | 'un') ? unit : units[0] || 'line'
  const priceUnit = basis === 'line' ? 'por linha' : `/${basis}`
  const comparable = product ? rows.filter(r => basis === 'line' || r.price?.unit === basis).map(r => ({ value: basis === 'line' ? r.item.total : r.price!.value, date: r.p.date, shop: r.p.shop })) : []
  const stats = priceStats(comparable)
  const daily = stats ? [...new Map(stats.sorted.map(r => [r.date, r]))].map(([,row]) => row) : []
  const low = Math.min(...daily.map(r => r.value)), high = Math.max(...daily.map(r => r.value)), span = high - low || high || 1
  const points = daily.map((r,n) => `${40 + n * 580 / Math.max(1,daily.length-1)},${130 - (r.value-low)/span*95}`).join(' ')
  return <section className="purchase-prices" aria-label="Histórico de preços">
    <div className="purchase-section-heading"><div><h2>Histórico de preços</h2><p className="purchase-muted">Compare o mesmo produto, na mesma unidade.</p></div></div>
    <div className="purchase-filters"><label>Produto / insumo<select value={product} onChange={e => {setProduct(e.target.value); setUnit('')}}><option value="">Todos os produtos</option>{products.map(([key,name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>Local<select value={shop} onChange={e => setShop(e.target.value)}><option value="">Todos os locais</option>{shops.map(([key,name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>De<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Até<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><label>Situação<select value={status} onChange={e => setStatus(e.target.value)}><option value="all">Todos</option><option value="paid">✓ Pago</option><option value="pending">○ A pagar</option></select></label></div>
    {from && to && from > to && <p role="alert">A data inicial deve ser anterior à final.</p>}
    {product && <>{<label className="purchase-basis">Comparar por<select value={basis} onChange={e => setUnit(e.target.value)}>{units.map(u => <option key={u} value={u}>R$/{u}</option>)}<option value="line">Valor total da linha</option></select></label>}
      {stats ? <><dl className="purchase-price-summary"><div><dt>Último preço</dt><dd>{fmtBRL(stats.last)} {priceUnit}</dd></div><div><dt>Menor</dt><dd>{fmtBRL(stats.min)} {priceUnit}</dd></div><div><dt>Maior</dt><dd>{fmtBRL(stats.max)} {priceUnit}</dd></div><div><dt>Variação no período</dt><dd>{stats.sorted.length > 1 ? `${stats.change > 0 ? '+' : ''}${stats.change.toLocaleString('pt-BR',{maximumFractionDigits:1})}%` : '—'}</dd></div><div><dt>Mais barato em</dt><dd>{stats.cheapest}</dd></div></dl><small>Comparação de {comparable.length} registros em R$ {priceUnit}, do primeiro ao último preço no período filtrado. Valores da compra, independentemente da quitação.</small>{basis === 'line' && <p className="purchase-muted">Valores totais das linhas; as quantidades podem ser diferentes. Informe as embalagens para comparar por kg, litro ou unidade.</p>}
      {daily.length >= 2 && <figure className="purchase-price-chart"><figcaption>Evolução · R$ {priceUnit} · último registro de cada dia</figcaption><svg viewBox="0 0 660 175" role="img" aria-label={`Evolução do preço: ${daily.map(r => `${r.date}, ${fmtBRL(r.value)} ${priceUnit}`).join('; ')}`}><line x1="40" y1="140" x2="620" y2="140" stroke="currentColor" opacity=".2"/><polyline points={points} fill="none" stroke="var(--cz-500)" strokeWidth="3"/>{daily.map((r,n) => <circle key={r.date} cx={40+n*580/(daily.length-1)} cy={130-(r.value-low)/span*95} r="4" fill="var(--cz-500)"><title>{r.date}: {fmtBRL(r.value)} {priceUnit}</title></circle>)}<text x="40" y="165" fill="currentColor" fontSize="12">{daily[0].date.split('-').reverse().join('/')}</text><text x="620" y="165" textAnchor="end" fill="currentColor" fontSize="12">{daily[daily.length-1].date.split('-').reverse().join('/')}</text></svg></figure>}
      </> : <p className="purchase-muted">Nenhum registro encontrado para esta comparação.</p>}
      {stats && rows.length > comparable.length && <p className="purchase-muted">{rows.length - comparable.length} registro(s) sem quantidade completa ou com outra unidade não entram na comparação.</p>}
    </>}
    {!product && <p className="purchase-muted">Selecione um produto para ver menor, maior e último preço.</p>}
    <div className="purchase-table-scroll" tabIndex={0} aria-label="Tabela de histórico de preços"><table className="purchase-table"><thead><tr><th>Produto</th><th>Valor da linha</th><th>Embalagem</th><th>Preço normalizado</th><th>Local</th><th>Data</th><th>Situação</th></tr></thead><tbody>{rows.map(({p,item,index,price}) => <tr key={`${p.id}-${index}`}><td>{item.name}</td><td>{fmtBRL(item.total)}</td><td>{item.quantity && item.packageSize && item.unit ? `${item.quantity} × ${item.packageSize} ${item.unit}` : 'Não informada'}</td><td>{price ? `${fmtBRL(price.value)}/${price.unit}` : '—'}</td><td>{p.shop || 'Não informado'}</td><td>{p.date.split('-').reverse().join('/')}</td><td><span className={`purchase-status ${purchaseDue(p) > 0 ? 'pending' : ''}`}>{paymentLabel(p)}</span></td></tr>)}</tbody></table></div>
    {!rows.length && <p className="purchase-empty">Nenhum preço encontrado com esses filtros.</p>}
  </section>
}
