import { changeItemQuantity } from '../purchase-scan'
import { IngredientPurchase, IngredientUnit, normalizedPrice, purchaseDue, purchaseTotal } from '../ingredients'
import { fmtBRL } from '../types'
export type PurchaseDraft = IngredientPurchase & { text: string; quickPaid?: number; quickDue?: number; expectedTotal?: number; scanConfidence?: number; scanConfirmed?: boolean; photoKind?: 'receipt' | 'product'; editingBefore?: IngredientPurchase }
export function PurchaseEditor({ draft, change, busy, onSave, onClose, onPhoto, onProcess, ignored }: {
  draft: PurchaseDraft; change: (draft: PurchaseDraft) => void; busy: boolean; onSave: () => void; onClose: () => void
  onPhoto: (file: File) => void; onProcess: () => void; ignored: string[]
}) {
  const patch = (part: Partial<PurchaseDraft>) => change({ ...draft, scanConfirmed: false, ...part })
  const total = purchaseTotal(draft)
  return <section className="purchase-editor" aria-label={draft.editingBefore ? 'Editar compra' : 'Nova compra'}>
    <div className="purchase-section-heading"><h2>{draft.editingBefore ? 'Editar compra' : 'Nova compra'}</h2><button className="btn btn-ghost" disabled={busy} onClick={onClose}>Fechar · manter rascunho</button></div>
    <fieldset disabled={busy}>
      <div className="purchase-fields"><label>Data da compra<input type="date" required value={draft.date} onChange={e => patch({ date: e.target.value })} /></label><label>Local / estabelecimento<input value={draft.shop} maxLength={200} placeholder="Ex.: Mercado X" onChange={e => patch({ shop: e.target.value })} /></label></div>
      <details className="purchase-import"><summary>Registrar só valores · sem listar produtos</summary>
        <p>Informe o que já pagou e o que ainda deve. Os valores entram no resumo financeiro como uma compra sem detalhamento.</p>
        <div className="purchase-fields"><label>Já pago (R$)<input aria-label="Valor já pago" type="number" min="0" max="1000000" step="0.01" value={draft.quickPaid ?? ''} onChange={e => patch({quickPaid:Number(e.target.value)})} /></label><label>A pagar (R$)<input aria-label="Valor a pagar" type="number" min="0" max="1000000" step="0.01" value={draft.quickDue ?? ''} onChange={e => patch({quickDue:Number(e.target.value)})} /></label></div>
        <button className="btn btn-secondary" disabled={(draft.quickPaid || 0) < 0 || (draft.quickDue || 0) < 0 || (draft.quickPaid || 0) + (draft.quickDue || 0) <= 0 || (draft.quickPaid || 0) + (draft.quickDue || 0) > 1000000} onClick={() => {
          if (draft.items.length && !confirm('Substituir os itens desta compra pelos valores informados?')) return
          const paid = Math.round((draft.quickPaid || 0) * 100) / 100, due = Math.round((draft.quickDue || 0) * 100) / 100
          patch({items:[{name:'Compra sem detalhamento',quantity:1,total:Math.round((paid + due) * 100) / 100}],paymentStatus:due > 0 ? 'pending' : 'paid',paidAmount:due > 0 ? paid : undefined,paidAt:undefined})
        }}>Usar estes valores</button>
      </details>
      <details className="purchase-import" open={!draft.items.length || undefined}><summary>Colar lista de compras</summary>
        <p>Cole a transcrição da nota, confira os produtos e salve. A data começa em hoje e o pagamento em Pago.</p>
        <label>Produtos e valores<textarea aria-label="Lista de compras" rows={7} value={draft.text} placeholder={'2x Farinha 1kg - 12,50\n5x Açúcar 1kg - 20,95\n1x Manteiga 500g - 20,90'} onChange={e => patch({ text: e.target.value })} /></label>
        <div className="purchase-section-heading"><small>Uma linha por produto: quantidade x nome - total da linha. O valor já inclui todas as unidades. Sem quantidade, usamos 1.</small><button className="btn btn-secondary" disabled={!draft.text.trim()} onClick={onProcess}>Preparar lista</button></div>
        <details><summary>Foto para conferência (opcional)</summary><p>A foto fica apenas anexada. Cole o texto já transcrito no campo acima.</p><label className="purchase-upload">Anexar foto<input aria-label="Foto ou print" type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { const f = e.target.files?.[0]; if (f) onPhoto(f); e.target.value = '' }} /></label></details>
        {ignored.length > 0 && <details><summary>{ignored.length} linhas não incluídas · conferir</summary><pre>{ignored.join('\n')}</pre></details>}
      </details>
      {draft.photo && <details><summary>Nota anexada</summary><img className="receipt-photo" src={draft.photo} alt="Nota anexada à compra" /><button className="btn btn-ghost" onClick={() => patch({ photo: undefined })}>Remover foto</button></details>}
      <div className="purchase-section-heading"><h3>Revisar produtos e quantidades</h3><button className="btn btn-secondary" onClick={() => patch({ items: [...draft.items, { name: '', total: 0 }] })}>+ Adicionar produto</button></div>
      {draft.items.length === 0 && <p className="purchase-muted">Cole a lista acima ou adicione um produto para começar.</p>}
      {draft.items.map((item, index) => {
        const updateItem = (part: Partial<typeof item>) => patch({ items: draft.items.map((i,n) => n === index ? { ...i, ...part } : i) })
        const normalized = normalizedPrice(item)
        return <div className="purchase-item-editor" key={index}>
          <div className="purchase-item-main"><label>Produto {index + 1}<input value={item.name} maxLength={500} onChange={e => updateItem({ name: e.target.value })} /></label><label>Quantidade<input aria-label={`Quantidade do produto ${index + 1}`} type="number" min="0.001" step="any" value={item.quantity ?? ''} placeholder="Conferir" onChange={e => updateItem(changeItemQuantity(item, Number(e.target.value)))} /></label><label>Preço por unidade (R$)<input aria-label={`Preço unitário do produto ${index + 1}`} type="number" min="0.01" step="0.01" value={item.unitPrice ?? (item.total && item.quantity ? Math.round(item.total / item.quantity * 100) / 100 : '')} placeholder="Conferir" onChange={e => updateItem({unitPrice:Number(e.target.value),quantity:item.quantity || 1,total:Math.round(Number(e.target.value) * (item.quantity || 1) * 100)/100})} /></label><label>Total da linha (R$)<input aria-label={`Total do produto ${index + 1}`} type="number" min="0.01" max="1000000" step="0.01" value={item.total || ''} onChange={e => updateItem({ total: Number(e.target.value), unitPrice: undefined })} /></label><button className="btn btn-ghost" aria-label={`Remover produto ${index + 1}`} onClick={() => patch({ items: draft.items.filter((_,n) => n !== index) })}>Remover</button></div>
          <details><summary>Peso / conteúdo da embalagem {normalized ? `· ${fmtBRL(normalized.value)}/${normalized.unit}` : '· opcional, para comparar preços'}</summary>
            <div className="purchase-fields purchase-package"><label>Conteúdo de cada embalagem<input aria-label={`Conteúdo do produto ${index + 1}`} type="number" min="0.001" step="any" value={item.packageSize ?? ''} placeholder="Ex.: 500" onChange={e => updateItem({ packageSize: e.target.value ? Number(e.target.value) : undefined })} /></label><label>Unidade<select aria-label={`Unidade do produto ${index + 1}`} value={item.unit || ''} onChange={e => updateItem({ unit: (e.target.value || undefined) as IngredientUnit | undefined })}><option value="">Não informada</option><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="l">litro</option><option value="un">unidade</option></select></label></div>
            <small>Ex.: 2 pacotes de 500 g = 1 kg no total. Para itens avulsos, use quantidade × 1 unidade.</small>
          </details>
        </div>
      })}
      {draft.photo && <div className="purchase-scan-review"><h3>Conferência da imagem</h3><p>Quantidade e preço por unidade recalculam o total da linha. O campo “Total da linha” também pode ser corrigido diretamente.</p><label>Total impresso na nota (R$)<input aria-label="Total da nota" type="number" min="0.01" step="0.01" value={draft.expectedTotal ?? ''} placeholder="Opcional, para comparar a soma" onChange={e => patch({expectedTotal:e.target.value ? Number(e.target.value) : undefined})} /></label>{draft.expectedTotal !== undefined && <p role="status">{Math.abs(total - draft.expectedTotal) < .01 ? '✓ A soma dos itens confere com o total informado.' : `⚠ Diferença de ${fmtBRL(Math.abs(total - draft.expectedTotal))} entre os itens e a nota. Confira itens ausentes, quantidades, descontos e taxas.`}</p>}{draft.scanConfidence !== undefined && draft.scanConfidence < 75 && <p>Leitura com baixa confiança: nomes e números precisam de revisão.</p>}<label className="purchase-check"><input type="checkbox" checked={!!draft.scanConfirmed} onChange={e => patch({scanConfirmed:e.target.checked})} />Conferi produtos, quantidades e valores com a imagem.</label></div>}
      <div className="purchase-payment"><div className="purchase-fields"><label>Situação do pagamento<select value={draft.paymentStatus || 'paid'} onChange={e => patch({ paymentStatus: e.target.value as 'paid' | 'pending', paidAmount: undefined, paidAt: undefined })}><option value="paid">✓ Pago</option><option value="pending">○ A pagar</option></select></label><div className="purchase-editor-total"><small>Total da compra</small><strong>{fmtBRL(total)}</strong></div></div>
        {draft.paymentStatus === 'pending' && <><div className="purchase-fields"><label>Para quem devo<input value={draft.creditor || ''} placeholder={draft.shop || 'Local ou pessoa'} maxLength={200} onChange={e => patch({ creditor: e.target.value })} /></label><label>Valor ainda devido (R$)<input type="number" min="0" max={total} step="0.01" value={purchaseDue(draft)} onChange={e => { const due = Number(e.target.value); patch({ paidAmount: Math.round((total - due) * 100) / 100 }) }} /></label><label>Vencimento (opcional)<input type="date" value={draft.dueDate || ''} onChange={e => patch({ dueDate: e.target.value })} /></label></div><small>Se parte já foi paga, informe somente o que falta. O restante entra em “Total pago”.</small></>}
        <details open={draft.note ? true : undefined}><summary>Observação (opcional)</summary><textarea aria-label="Observação da compra" value={draft.note || ''} rows={2} maxLength={2000} onChange={e => patch({ note: e.target.value })} /></details>
      </div>
      <div className="purchase-section-heading"><small>Confira produtos e valores da nota antes de salvar.</small><button className="btn btn-primary" disabled={!draft.items.length || !!draft.photo && !draft.scanConfirmed} onClick={onSave}>{draft.editingBefore ? 'Salvar alterações' : 'Salvar compra'}</button></div>
    </fieldset>
  </section>
}
